name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v1.2.5
      with:
        # GitHub repository where assets will be deployed (default current)
        repo: current# optional
        # Git branch where assets will be deployed
        target_branch: gh-pages #optional, default is gh-pages
        # Create incremental commit instead of doing push force
        keep_history: false # optional, default is false
        # Allow an empty commit to be created
        allow_empty_commit: true # optional, default is true
        # Build directory to deploy
        build_dir: ./
